[package]
name = "epg"
version = "0.1.0"
authors = ["Cesbo Developers Team"]
edition = "2018"

[dependencies]
error-rules = "0.2"
http = { path = "../libhttp" }
mpegts = { path = "../libmpegts" }
chrono = "0.4"
xml-rs = "0.8"
libflate = "0.1"
